reject:
  # Updating to ESLint 10 is blocked by some plugins, including:
  # https://github.com/eslint-config/airbnb-extended/issues/65
  - eslint
  # https://github.com/sveltia/sveltia-cms/issues/540
  - terra-draw-leaflet-adapter
  # Block upgrade to TypeScript 7
  # https://github.com/sveltejs/language-tools/issues/3063 and more
  - typescript
