cooldown: 1
reject:
  # https://github.com/sveltejs/svelte-eslint-parser/issues/828
  - eslint
  - eslint-plugin-svelte
  # https://github.com/sveltia/sveltia-cms/issues/540
  - terra-draw-leaflet-adapter
