cooldown: 1
reject:
  # blocked by the ESLint v9 support of eslint-config-airbnb-base
  # https://github.com/airbnb/javascript/issues/2961
  - eslint
  - eslint-plugin-svelte
  # https://github.com/sveltia/sveltia-cms/issues/540
  - terra-draw-leaflet-adapter
