reject:
  # Updating to ESLint 10 is blocked by some plugins, including:
  # https://github.com/eslint-config/airbnb-extended/issues/65
  - eslint
  # https://github.com/sveltia/sveltia-cms/issues/540
  - terra-draw-leaflet-adapter
  # Updating to TypeScript 6 is blocked by
  # https://github.com/sveltejs/svelte-preprocess/pull/675
  - typescript
