cooldown: 1
reject:
  # Updating to ESLint 10 is blocked by some plugins, including:
  # https://github.com/import-js/eslint-plugin-import/issues/3227
  # https://github.com/eslint-config/airbnb-extended/issues/65
  - eslint
  # https://github.com/sveltia/sveltia-cms/issues/540
  - terra-draw-leaflet-adapter
  # Updating to TypeScript 6 is blocked by various unmet peer dependencies
  - typescript
  # 3.1.0 causes test failures for some reason
  - eslint-config-airbnb-extended
