allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  svelte-preprocess: true
  unrs-resolver: false

engineStrict: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@sveltia/*"
  # Apply bug fix
  # https://github.com/sveltejs/svelte-preprocess/releases/tag/svelte-preprocess%406.0.5
  - svelte-preprocess
