minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@sveltia/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - es5-ext
  - esbuild
  - svelte-preprocess

overrides:
  esbuild@<=0.24.2: ">=0.25.0"
  glob@>=11.0.0 <11.1.0: ">=11.1.0"
