allowBuilds:
  unrs-resolver: false

engineStrict: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@sveltia/*'

auditConfig:
  ignoreGhsas:
    # dev dependencies only, ignore for now
    # https://github.com/advisories/GHSA-rgw5-rvv9-x895
    - GHSA-rgw5-rvv9-x895
