import { describe, expect, test } from 'vitest';

import { PULL_REQUEST_DESCRIPTION } from '$lib/services/backends/git/shared/pull-requests';

describe('shared pull request constants', () => {
  test('describes a request as one the CMS opened', () => {
    expect(PULL_REQUEST_DESCRIPTION).toBe('Automatically generated by Sveltia CMS');
  });
});
